---
apiVersion: v1
kind: Secret
metadata:
  name: github-private-repo-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:gauravgirase/privateAPP.git
  sshPrivateKey: |
  <private_key> # paste private key here
  insecure: "false"
  enableLfs: "true"
